### ISSUE TITLE
How to specify language if we know the language of the article?

### ISSUE THREAD

**Issue by wahyusaputra** [fhamborg/news-please#100]
Would you please enlighten me, how to specify language for the article being parsed?

In newspaper3k I normally set it like this:

`
from newspaper import Article

url = 'https://news.detik.com/berita/d-4492222/ke-dpr-psi-berikan-gabut-award-untuk-anggota-dewan?tag_from=wp_hl_judul'
article = Article(url, language='id')

article.download()
article.parse()
print(article.title)
print(article.text)`

**Comment by fhamborg** [comment]
There's no benefit in setting the language if you already know it. So, for your record, you could just set it in the resulting article object once news-please is finished. For newspaper3k, afaik, setting the language beforehand will help to better determine keywords and other of the NLP related functionality.
