### ISSUE TITLE
Cannot import NewsPlease from newsplease...

### ISSUE THREAD

**Issue by theChef613** [fhamborg/news-please#102]
Installation seemed to run just fine without any errors. Tried to run the first tutorial code after installation. Using PyCharm 2019.1.1 and have run other programs without any issues. 

running the following will reproduce the behavior:
from newsplease import NewsPlease
article = NewsPlease.from_url('https://www.nytimes.com/2017/02/23/us/politics/cpac-stephen-bannon-reince-priebus.html?hp')
print(article.title)

Expected to see the article title from the url. get the following error message: ImportError: cannot import name 'NewsPlease' from 'newsplease'

Using Windows 10
Python 3.7.3
latest newsplease version 1.3.13 (fresh install)

Thank you!

**Comment by theChef613** [comment]
I feel so silly but I solved the issue... the python file I was writing was also called "newsplease.py" and it interfered with the import. I apologize...

**Comment by fhamborg** [comment]
great that you got it up and running :)
