### ISSUE TITLE
How to make it faster?

### ISSUE THREAD

**Issue by jmy48** [fhamborg/news-please#103]
Hi, very potentially useful tool!

Running it on a Macbook Pro 2018 over a 3 year time range with 3 sources generates 1 article per second. We want millions of articles that contain a keyword, so we'll first mine the entire website and then filter out irrelevant articles (meaning we want possibly 10s of millions of raw articles). This is obviously intractible, taking years to do.

What are some ways we can make it faster? We've increased the number of crawlers, daemons, and concurrent requests on the same domain, but not sure if it helps. We're also only using the date extractor and the readability extractor in the pipeline, and recursive crawlers (as when we tested sitemap crawlers, they got stuck and were incredibly slow). Is it possible to get our task done on the order of hours?

**Comment by fhamborg** [comment]
I'd focus on identifying the main cause for the low speed. Typically the news outlets limit crawling, e.g, by introducing time outs or lowering connection speed if they detect that a single IP is crawling suspiciously many articles. 

Alternative idea: Check out the commoncrawl.org news archive, which news-please supports out of the box. Assumed that it contains the news outlets you're interested in, this should be much faster.
