### ISSUE TITLE
A callback hook when a WARC is fully processed.

### ISSUE THREAD

**Issue by sb895** [fhamborg/news-please#105]
In the commoncrawl_extractor's main loop in the **__process_warc_gz_file** function, would it be possible to add a call back when the processing of the WARC file is complete.  Currently the only call back is when an article is extracted (which is helpful),  but I need to run some code at the end of extraction of an entire WARC file, is there currently a way to do this using the commoncrawl_extractor ?

**Comment by fhamborg** [comment]
Sure, we will gladly accept any PR that adds this.
