### ISSUE TITLE
Using news-please to parse all of the articles that come up from a search term on a news website

### ISSUE THREAD

**Issue by leilahawa** [fhamborg/news-please#111]
Hello,

I would like to use news-please to parse all of the articles that come up when searching a term on a news page (ie - searching the term "pretzels" on nytimes.com, which would generate the following url: https://www.nytimes.com/search?query=pretzels). I am looking to collect the full text, article title, publication date, authors, url, etc. of each resulting article. Is it possible to use news-please to accomplish this? If so, any advice on how to do this would be much appreciated!

Thanks!

**Comment by fhamborg** [comment]
I don't see a way how this could be accomplished out of the box with news-please. One issue is also that how to address this task highly depends on the website that one wants to crawl from.
