### ISSUE TITLE
How to download article links from downloaded HTML?

### ISSUE THREAD

**Issue by hockeybro12** [fhamborg/news-please#122]
Hello,

I was able to download HTML snapshots of a website from WayBack Machine to my computer using the wayback machine downloader library.

I want to use news-please on these HTMLs to extract all the articles that were present on the website for that given day that the snapshot is from. I see in the documentation that news-please can be run on HTML url's and web links, but how can I run it to crawl downloaded HTMLs?

I am doing this because if I use a repo like `newspaper` to get articles from a given site, it only returns recent ones (probably because it cannot crawl that far). Thus, I am hoping that if I can crawl a snapshot from a year ago, I can get articles from that site for that time. I saw that `news-please` crawler was able to crawl certain sites like NYTimes, so I'm hoping that it could help me crawl saved HTMLs, or at least extract the article URL from saved HTML webpages.

**Comment by fhamborg** [comment]
have you tried using `NewsPlease.from_html(html, url)`?

**Comment by hockeybro12** [comment]
According to the comments of that function, it seems that it would just be able to extract information from an article HTML, not crawl the site. As I have the HTML snapshot from many timestamps via WayBack Machine, I would like to crawl the site at each of those timestamps. So my HTML is from the website home page, not the article. The reason I want to do this is because I have noticed that crawling just from the current iteration of the website homepage sometimes doesn't get all the articles.

`This function does not invoke scrapy but only uses the article extractor`

Regardless, I will try `NewsPlease.from_html` incase it does actually handle more than just article HTMLs.

**Comment by fhamborg** [comment]
What specifically/technically do you mean by "HTML snapshot"? Is it in HTML format or something else? Out-of-the box, news-please lets you crawl from a HTML string or from an URL (among others, but these two are IMO the potentially relevant functions for your use case).

**Comment by hockeybro12** [comment]
By HTML snapshot, I mean the HTML of the page. For example, I would have the HTML (index.html) of the homepage of DailyMail from last August. A package such as [WayBackMachine downloader ](https://github.com/hartator/wayback-machine-downloader) allows me to get this.

So I can convert the HTML to a string. Does the `NewsPlease.from_html` function allow me to crawl? Because it seems like it doesn't invoke scrapy.

**Comment by fhamborg** [comment]
Okay got you. The required functionality is not supported unfortunately by news-please; it would require that you add that functionality. IMO the easiest (perhaps not best) option is to extract all URLs from the HTML at hand (maybe using beautiful soup) and then pass these URLs to news-please.

**Comment by hockeybro12** [comment]
So I can pass the URLs to news-please to crawl recursively from that URL. For this, should I use the python API or the command line tool?

Since news-please can do this from a URL, is there something to build off of to do it from a HTML? Or do you think it would be too complex and it's better/easer to do it from scratch (using beautiful soup).

**Comment by fhamborg** [comment]
1) You have to use the CLI. 
2) You probably will find that functionality in the code, but I'd just quickly implemented it using beautiful soup, if you just plan to test this.

**Comment by hockeybro12** [comment]
Ok, thanks so much for the help, I will test it out and let you know if I have any questions!
