### ISSUE TITLE
Where can I find the download link about CCNC dataset?

### ISSUE THREAD

**Issue by OleNet** [fhamborg/news-please#123]
Hello,

I want to download the dataset which was mentioned in the readme announcements, and a-mail had been sent to felix.hamborg@uni-konstanz.de (the signature is Liu Jiaxiang). Could you check the email, and check whether I'm qualified to download the dataset?

Thanks!

**Comment by fhamborg** [comment]
We have replied to you already at the same day you sent the mail, please check your inbox (your mail was olenet.cn@gmail.com). Thanks!

**Comment by fhamborg** [comment]
Please refrain from sending us multiple requests on the exact same thing via different communication channels. We have only so much resources to run this open source project in our spare time.
