### ISSUE TITLE
arxiv.org article pages not processed correctly

### ISSUE THREAD

**Issue by sadaszewski** [fhamborg/news-please#125]
**Describe the bug**
When parsing for example https://arxiv.org/abs/1902.10740 I would expect newsplease to recognize the content as either title and description or title and text, instead I get the "Donate to arXiv" as title and "Please join the Simons Foundation and our generous member organizations in supporting arXiv during our giving campaign September 23-27. 100% of your contribution will fund improvements and new initiatives to benefit arXiv's global scientific community." as text.

**To Reproduce**
NewsPlease().from_url('https://arxiv.org/abs/1902.10740')

**Expected behavior**
I would expect newsplease to recognize the correct part of the content as either title and description or title and text.

**Log**
N/A

**Versions (please complete the following information):**
 - OS: Linux
 - Python Version: 3.6
 - news-please Version: latest

**Comment by fhamborg** [comment]
Hi, thanks for the report. arxiv.org is not a news website but a academic publication / preprint website, thus you should not expect news-please to work properly, which aims to extract information from news websites. If you wish to pursue this issue, though, I recommend that you go to newspaper3k, which is the underlying library that news-please uses to extract such information.

**Comment by sadaszewski** [comment]
Wouldn't it fail though on any page containing a similar donation div before the content div?
