### ISSUE TITLE
MongoDB Implementation

### ISSUE THREAD

**Issue by jacarrasco** [fhamborg/news-please#127]
Hi,
I tried to do a pull request but it seems it is not working. I copy below the code. 
I tested and it works.
It mainly add the data from the JSONs into a MongoDB. It was useful for me because it makes it very easy for me to handle the data.

See below the code.
---------------------------------------------------------------------------
In pipelines.py:

...
from scrapy.exceptions import DropItem
from pymongo import MongoClient
from pymongo.errors import ConnectionFailure
....
class MongoDBStorage(ExtractedInformationStorage):
    """
    Handles remote storage of the meta data in MongoDB
    """
    log = None
    cfg = None
    database = None
    conn = None
    host = None
    port = None
    cursor = None
    dbdata = None
    cursordata = None

    # init database connection
    def __init__(self):

        self.log = logging.getLogger(__name__)

        self.cfg = CrawlerConfig.get_instance()
        self.database = self.cfg.section("MongoDB")
        try:
            # Establish DB connection
            # Closing of the connection is handled once the spider closes
            self.conn = MongoClient(host=self.database["host"],
                                    port=self.database["port"],
                                    username=self.database["username"],
                                    password=self.database["password"])

            self.dbdata = self.conn[self.database["db"]]
            #self.cursor = self.conn.cursor()
        except ConnectionFailure as error:
            self.running = False
            self.log.error("Failed to connect to MongoDB, this module will be deactivated. "
                           "Please check if the database is running and the config is correct: %s" % error)

----------------------------------------------------------------------------

In __main__.py:

https://pastebin.com/X7kQDpgd

----------------------------------------------------------------------------

In config.cfg:

[MongoDB]

# MongoDB-Connection required for saving meta-informations
host = localhost
port = 27017
db = newsplease
username = ""
password = ""

**Comment by afuetterer** [comment]
Hi, I am wondering: What is the status of this issue?
@jacarrasco Can I help you with a PR?

I took the code you provided and added an process_item() implementation. It seems to be working just fine.
