### ISSUE TITLE
article.text returns None on english article

### ISSUE THREAD

**Issue by ysig** [fhamborg/news-please#133]
Hi,

I post a webpage where I used your library and it didn't work (in case you want feedback)

To test run:

```python
url = "https://www.naftemporiki.gr/story/1536265/weather-front-with-heavy-rains-causes-problems-throughout-greece"
from newsplease import NewsPlease
article = NewsPlease.from_url(url)
assert article.text is None
# where it shouldn't
```

Although a greek website it is written in English so it should work. Also it behaves like that on all english entries of this website.

Thanks a lot.

**Comment by fhamborg** [comment]
Hi, could you post the content of `title` as well as of `description` please?

**Comment by Oleg-A-LLIto** [comment]
Looks like I have the same issue.
Tried it with different websites, all of the articles are in English, so I don't quite believe it's a matter of an article at all.
Here are some title and description examples:
```
Title: U.S. Supreme Court Allows 'Remain In Mexico' Program To Continue
Text: None
Description: The high court will allow the Trump administration's "Remain in Mexico" policy to stand across the entire southern border. The decision marks another immigration victory for the White House.
```
Looks like nothing is off the wall for me. Somehow it fails to parse the text, though.

**Comment by Oleg-A-LLIto** [comment]
@ysig 
I managed to solve it by rolling back my news-please to 1.3.14
`pip install news-please==1.3.14 --force-reinstall`
Looks like this bug appeared in one of 1.14.x updates
Waiting for a fix, though

**Comment by ysig** [comment]
Nice

**Comment by berkayberkman** [comment]
> @ysig
> I managed to solve it by rolling back my news-please to 1.3.14
> `pip install news-please==1.3.14 --force-reinstall`
> Looks like this bug appeared in one of 1.14.x updates
> Waiting for a fix, though

Thank you! I hope they can fix this bug.

**Comment by fhamborg** [comment]
should be fixed in the latest release

**Comment by pmehler** [comment]
I was having the issue of article.text returning 'None' as well, but noticed that the json key for the article text was actually called 'maintext' and was able to extract the proper info with: 

`from newsplease import NewsPlease
article = NewsPlease.from_url('https://www.cnn.com/2020/05/03/opinions/michelle-lujan-grisham-biden-vp-pick-simon/index.html')

print(article.maintext)`

The example json in the readme has 'text' as the json key for the article text instead of 'maintext', which confused me at first.

**Comment by fhamborg** [comment]
@pmehler thanks, I fixed that!
