### ISSUE TITLE
Use news please with google news

### ISSUE THREAD

**Issue by quasar16** [fhamborg/news-please#136]
I am trying to use news please with google news search but I am not sure which crawler to use.
Can you help me?

**Versions (please complete the following information):**
 - OS: [e.g. MacOS 10.15]
 - Python Version [e.g. 3.7]
 - news-please Version [e.g. 1.2]

**Comment by fhamborg** [comment]
NP is not designed to crawl from news aggregators, such as GNews. Would be interesting to see, if and how well it performs, though. Feel free to post your results and insights here.
