### ISSUE TITLE
Some of the values in article.get_dict() are None

### ISSUE THREAD

**Issue by juanluisrto** [fhamborg/news-please#139]
**Mandatory**
* [ x] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [ x] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

**Describe the bug**
When I extract the info from an url, I can get the main text accessing `article.maintext`, but when I request the data as a dict, `maintext == None`

**To Reproduce**
``` 
from newsplease import NewsPlease
url = "https://www.elmundo.es/ciencia-y-salud/salud/2020/03/19/5e73013afc6c83d6438b462d.html"
article = NewsPlease.from_url(url)
print(article.maintext[:200])
print(article.get_dict()["maintext"] == None)
```

**Expected behavior**
I expect to get the same text via the get_dict() method

**Log**
Output of the above example is:
```
El coronavirus sigue golpeando a Europa, especialmente a Italia, donde el jefe del Gobierno ha anunciado que el confinamiento se ampliará, y a España, donde los casos siguen subiendo
3.500 contagiados
True
```
**Versions (please complete the following information):**
 - OS: [e.g. MacOS 10.15.2]
 - Python Version [e.g. 3.7.6]
 - news-please Version [e.g. 1.4.25]

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [x] personal
* [x] academic
* [ ] business
* [ ] other

**Comment by fhamborg** [comment]
Thanks for the report! Should be fixed with the latest commit (also available on pip): 39aff553beefe30dac3d359201294291a9f6f57e Please reopen in case the issue persists.
