### ISSUE TITLE
Javascript is disabled on your browser AND Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

### ISSUE THREAD

**Issue by lalimili6** [fhamborg/news-please#150]
Hi
when I use Library mode in python sometimes get these errors. How can fix them?
`url= "https://www.varzesh3.com/news/1403838/%D9%88%D8%A7%D9%84%D9%86%D8%B3%DB%8C%D8%A7-%D8%AD%D8%B3-%D9%85%DB%8C%E2%80%8C-%DA%A9%D9%86%D9%85-21-%D8%B3%D8%A7%D9%84-%D8%AF%D8%A7%D8%B1%D9%85"`

 `article = NewsPlease.from_url(url)`

`print(article.maintext)`

`Javascript is disabled on your browser, to have the best experience of using varzesh3.com, enable it.`

AND

`url='https://www.tabnak.ir/fa/news/129424/%D9%BE%D8%B1%D8%AF%D8%B1%D8%A2%D9%85%D8%AF%D8%AA%D8%B1%DB%8C%D9%86-%D9%85%D8%B4%D8%A7%D8%BA%D9%84-it-%DA%A9%D8%AF%D8%A7%D9%85%D9%86%D8%AF'`

`article = NewsPlease.from_url(url)`
`Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.`

best regards

**Comment by fhamborg** [comment]
Can you please reopen this bug report using the corresponding template? Thanks.
