### ISSUE TITLE
Javascript is disabled on your browser

### ISSUE THREAD

**Issue by lalimili6** [fhamborg/news-please#151]
Related issues:
#150

**Describe the bug**
when I use Library mode in python sometimes get this message. 
```
url= "https://www.varzesh3.com/news/1403838/%D9%88%D8%A7%D9%84%D9%86%D8%B3%DB%8C%D8%A7-%D8%AD%D8%B3-%D9%85%DB%8C%E2%80%8C-%DA%A9%D9%86%D9%85-21-%D8%B3%D8%A7%D9%84-%D8%AF%D8%A7%D8%B1%D9%85"

article = NewsPlease.from_url(url)

print(article.maintext)
```

```Javascript is disabled on your browser, to have the best experience of using varzesh3.com, enable it.```

**Versions (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS
 - Python 3.6.7
 - news-please Version 1.5.03

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [. ] personal
* [ .] academic
* [ ] business
* [ ] other
* Some information on your project: 
using crawled text to make language model for speech recognition. I used Kaldi speech recognition code

best regards

**Comment by fhamborg** [comment]
closing this, as this question has been answered a few times already
