### ISSUE TITLE
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER

### ISSUE THREAD

**Issue by lalimili6** [fhamborg/news-please#152]
Related issues:
#150

**Describe the bug**
I get error below when using python library code:
```
url='https://www.tabnak.ir/fa/news/129424/%D9%BE%D8%B1%D8%AF%D8%B1%D8%A2%D9%85%D8%AF%D8%AA%D8%B1%DB%8C%D9%86-%D9%85%D8%B4%D8%A7%D8%BA%D9%84-it-%DA%A9%D8%AF%D8%A7%D9%85%D9%86%D8%AF'

article = NewsPlease.from_url(url)
Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.
```
**Versions (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS
 - Python 3.6.7
 - news-please Version 1.5.03

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [ .] personal
* [. ] academic
* [ ] business
* [ ] other
* Some information on your project: 
using crawled text to make language model for speech recognition. I used Kaldi speech recognition code

best regards

**Comment by fhamborg** [comment]
closing this, as this question has been answered a few times already and the issue unfortunately not containing all required information (as it does not use the template)
