### ISSUE TITLE
language filtering

### ISSUE THREAD

**Issue by lalimili6** [fhamborg/news-please#153]
Is it possible to add language filtering to config?
It is good for Some websites that have multilingual versions

 - OS: Ubuntu 18.04.1 LTS
 - Python 3.6.7
 - news-please Version 1.5.03

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [x] personal
* [x] academic

* Some information on your project: 
using crawled text to make language model for speech recognition. I used Kaldi speech recognition code

best regards

**Comment by fhamborg** [comment]
closing this, as this question has been answered a few times already and the issue unfortunately not containing all required information (as it does not use the template)
