### ISSUE TITLE
[Error Crawling March data][[newsplease.crawler.commoncrawl_extractor] ERROR: Unexpected error: <class 'PermissionError'>]

### ISSUE THREAD

**Issue by sara-02** [fhamborg/news-please#163]
**Mandatory** 
- [x]  I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).

* [x] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

Related issues:
* add them here

**Describe the bug**
While trying to crawl the March Archieve of common-crawler, I am facing the following error:
``
[newsplease.crawler.commoncrawl_extractor] ERROR: Unexpected error: <class 'PermissionError'>
``
it is trying to download the https://commoncrawl.s3.amazonaws.com/crawl-data/CC-NEWS/2020/03/CC-NEWS-20200309003729-01135.warc.gz and few warcs around it again and agin but getting stuck with the above error.

The current downloaded WARC list is stuff after/at this point
```
https%3A%2F%2Fcommoncrawl.s3.amazonaws.com%2Fcrawl-data%2FCC-NEWS%2F2020%2F03%2FCC-NEWS-20200309003729-01135.warc.gz
https%3A%2F%2Fcommoncrawl.s3.amazonaws.com%2Fcrawl-data%2FCC-NEWS%2F2020%2F03%2FCC-NEWS-20200309062503-01137.warc.gz
https%3A%2F%2Fcommoncrawl.s3.amazonaws.com%2Fcrawl-data%2FCC-NEWS%2F2020%2F03%2FCC-NEWS-20200309102435-01139.warc.gz
https%3A%2F%2Fcommoncrawl.s3.amazonaws.com%2Fcrawl-data%2FCC-NEWS%2F2020%2F03%2FCC-NEWS-20200309130750-01141.warc.gz
https%3A%2F%2Fcommoncrawl.s3.amazonaws.com%2Fcrawl-data%2FCC-NEWS%2F2020%2F03%2FCC-NEWS-20200309153704-01143.warc.gz

```
I also have the `my_continue_after_error = True`
**To Reproduce**
Run the news piece crawler with filter dates set to March 1st 2020 and March 20th 2020.

**Expected behavior**
Either a proper log of why this is occuing, or the data should move on with collecting rest of the WARCs.

**Log**
```
ERROR:newsplease.crawler.commoncrawl_extractor:Unexpected error: <class 'PermissionError'>
2020-06-07 18:41:27 [newsplease.crawler.commoncrawl_extractor] ERROR: Unexpected error: <class 'PermissionError'>
ERROR:newsplease.crawler.commoncrawl_extractor:Unexpected error: <class 'PermissionError'>
2020-06-07 18:41:27 [newsplease.crawler.commoncrawl_extractor] ERROR: Unexpected error: <class 'PermissionError'>
ERROR:newsplease.crawler.commoncrawl_extractor:Unexpected error: <class 'PermissionError'>
2020-06-07 18:41:27 [newsplease.crawler.commoncrawl_extractor] ERROR: Unexpected error: <class 'PermissionError'>
ERROR:newsplease.crawler.commoncrawl_extractor:Unexpected error: <class 'PermissionError'>
2020-06-07 18:41:27 [newsplease.crawler.commoncrawl_extractor] ERROR: Unexpected error: <class 'PermissionError'>
ERROR:newsplease.crawler.commoncrawl_extractor:Unexpected error: <class 'PermissionError'>
2020-06-07 18:41:27 [newsplease.crawler.commoncrawl_extractor] ERROR: Unexpected error: <class 'PermissionError'>
```
After this it tries to download the `NEWS%2F2020%2F03%2FCC-NEWS-20200309003729-01135.warc.gz
https%3A%2F%2Fcommoncrawl.s3.amazonaws.com%2Fcrawl-data%2FCC-NEWS%2F2020%2F03%2FCC-NEWS-20200309062503-01137.warc.gz
` on wards again, but fails. The code is stuck is some loop.

**Versions (please complete the following information):**
 - OS: Ubuntu
 - Python Version 3.6.8
 - news-please Version: latest from github master clone

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [ ] personal
* [x] academic
* [ ] business
* [ ] other
* Some information on your project:

**Comment by sara-02** [comment]
Any help would be appreciated.

**Comment by fhamborg** [comment]
I cant reproduce this here, neither on Mac nor Ubuntu. Is this still an issue?

**Comment by sara-02** [comment]
Hey @fhamborg On my local Ubuntu, even I am not facing this issue. This error occurred while I tried news-please on a server. And I am still facing this issue.

**Comment by fhamborg** [comment]
pls feel free to reopen this if this is still an issue

**Comment by sara-02** [comment]
Just leaving a comment for future reference, I was able to overcome this by not relying on the script to create the directory for me, instead when I created the directory beforehand, this error did not occur.
