### ISSUE TITLE
Using bytes HTML is significantly slower than str HTML for parsing content

### ISSUE THREAD

**Issue by amjltc295** [fhamborg/news-please#164]
**Mandatory**
* [v] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [v] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

Related issues:
* None

**Describe the bug**
Using bytes HTML is significantly slower than str HTML for parsing content (NewsPlease.from_html) -- is there a reason for this?

**To Reproduce**
Dependencies
```bash
pip install news-please
pip install trafilatura
```
Script
```python
from time import time
from copy import deepcopy

import trafilatura
from newsplease import NewsPlease
from newsplease.crawler.simple_crawler import SimpleCrawler
import lxml
from newspaper import Article
from readability import Document


url = 'https://www.fox5vegas.com/news/black-friday-shoppers-looking-for-best-deals/video_c236dde4-65c2-5bd6-983e-8b7b97a67a46.html'

t = time()
html_bytes = SimpleCrawler.fetch_url(url)
print(f"NewsPlease SimpleCrawler \nCrawling time: {time() - t}, html_type: {type(html_bytes)}")

t = time()
# Note that it's similar to use
# html_str = html_bytes.decode('utf-8')
html_str = trafilatura.fetch_url(url)
print(f"trafilatura \nCrawling time: {time() - t}, html_type: {type(html_str)}")

for html_x in [html_bytes, html_str]:
    print(f"\nType {type(html_x)}")

    t = time()
    article = NewsPlease.from_html(html_x)
    print(f"HTML to content total time: {time() - t}")

    t = time()
    Document(deepcopy(html_x)).summary()
    print(f"Readability Document parsing time: {time() - t}")

    t = time()
    article = Article('')
    article.set_html(html_x)
    article.parse()
    print(f"Newspaper Article  parsing time: {time() - t}")

    t = time()
    lxml.html.fromstring(html_x)
    print(f"lxml html parsing time: {time() - t}")
```
Result
```bash
NewsPlease SimpleCrawler
Crawling time: 1.1815030574798584, html_type: <class 'bytes'>
trafilatura
Crawling time: 0.8717167377471924, html_type: <class 'str'>

Type <class 'bytes'>
HTML to content total time: 9.906309843063354
Readability Document parsing time: 1.6843905448913574
Newspaper Article  parsing time: 3.266613245010376
lxml html parsing time: 0.0048770904541015625

Type <class 'str'>
HTML to content total time: 0.222869873046875
Readability Document parsing time: 0.03697085380554199
Newspaper Article  parsing time: 0.09907245635986328
lxml html parsing time: 0.004587888717651367
```
**Expected behavior**
Decode html in SimpleCrawler._fetch_url?

**Versions (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python Version 3.7.0
 - news-please Version 1.5.3

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [ ] personal
* [ ] academic
* [ ] business
* [ ] other
* Some information on your project:

**Comment by fhamborg** [comment]
Very interesting. Do you want to submit a PR, so that we can have a closer look at it and in the best case already merge it?

**Comment by adbar** [comment]
Hi, I'm the author of [trafilatura](https://github.com/adbar/trafilatura).

If I understand correctly the first processing difference can be explained first by a lazy string decoding and then by using [cchardet](https://github.com/PyYoshi/cChardet).

```
def isutf8(data):
    """Simple heuristic to determine if a bytestring uses standard unicode"""
    try:
        data.decode('UTF-8')
    except UnicodeDecodeError:
        return False
    else:
        return True

def detect_encoding(bytesobject):
    """Read the bytestring and return its encoding"""
    # unicode-test
    if isutf8(bytesobject):
        return 'UTF-8'
    # try cchardet
    if cchardet is not None:
        guess = cchardet.detect(bytesobject)
        return guess['encoding']
    return None
```

I don't know why a bytestring would be significantly slower but I guess it has to do with the way LXML parses it. Encoding mess workarounds in LXML are also more thorough, results won't be exactly the same for these cases.

PS: It's not only about speed, `trafilatura` probably achieves a better recall, at least on my data, here is an [evaluation](https://trafilatura.readthedocs.io/en/latest/evaluation.html) ;)

**Comment by fhamborg** [comment]
thanks for the PR! its already merged into master after a few tests. will upload it into a new pypi version once i got more time for more comprehensive tests
