### ISSUE TITLE
error in executing commoncrawl.py 

### ISSUE THREAD

**Issue by Prateek-Tyagi** [fhamborg/news-please#166]
**python3 -m newsplease.examples.commoncrawl** when executing this.. it throws this error
```
my_local_download_dir_warc=./cc_download_warc/
my_local_download_dir_article=./cc_download_articles/
delete_warc_after_extraction=False
my_number_of_extraction_processes=1
INFO:newsplease.crawler.commoncrawl_crawler:executing: aws s3 ls --recursive s3://commoncrawl/crawl-data/CC-NEWS/ --no-sign-request > .tmpaws.txt && awk '{ print $4 }' .tmpaws.txt && rm .tmpaws.txt
INFO:newsplease.crawler.commoncrawl_crawler:found 2 files at commoncrawl.org
INFO:newsplease.crawler.commoncrawl_crawler:creating extraction process pool with 1 processes
INFO:newsplease.crawler.commoncrawl_extractor:found local file ./cc_download_warc/https%3A%2F%2Fcommoncrawl.s3.amazonaws.com%2F, not downloading again due to configuration
Traceback (most recent call last):
  File "/home/prateek/.local/lib/python3.6/site-packages/warcio/recordloader.py", line 236, in _detect_type_load_headers
    rec_headers = self.arc_parser.parse(stream, statusline)
  File "/home/prateek/.local/lib/python3.6/site-packages/warcio/recordloader.py", line 312, in parse
    raise StatusAndHeadersParserException(msg, parts)
warcio.statusandheaders.StatusAndHeadersParserException: Wrong # of headers, expected arc headers ['uri', 'ip-address', 'archive-date', 'content-type', 'length'], Found ['<?xml', 'version="1.0"', 'encoding="UTF-8"?>']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/prateek/.local/lib/python3.6/site-packages/newsplease/examples/commoncrawl.py", line 172, in <module>
    main()
  File "/home/prateek/.local/lib/python3.6/site-packages/newsplease/examples/commoncrawl.py", line 168, in main
    continue_process=True)
  File "/home/prateek/.local/lib/python3.6/site-packages/newsplease/crawler/commoncrawl_crawler.py", line 320, in crawl_from_commoncrawl
    log_pathname_fully_extracted_warcs=__log_pathname_fully_extracted_warcs)
  File "/home/prateek/.local/lib/python3.6/site-packages/newsplease/crawler/commoncrawl_crawler.py", line 230, in __start_commoncrawl_extractor
    log_pathname_fully_extracted_warcs=__log_pathname_fully_extracted_warcs)
  File "/home/prateek/.local/lib/python3.6/site-packages/newsplease/crawler/commoncrawl_extractor.py", line 338, in extract_from_commoncrawl
    self.__run()
  File "/home/prateek/.local/lib/python3.6/site-packages/newsplease/crawler/commoncrawl_extractor.py", line 292, in __run
    self.__process_warc_gz_file(local_path_name)
  File "/home/prateek/.local/lib/python3.6/site-packages/newsplease/crawler/commoncrawl_extractor.py", line 231, in __process_warc_gz_file
    for record in ArchiveIterator(stream):
  File "/home/prateek/.local/lib/python3.6/site-packages/warcio/archiveiterator.py", line 110, in _iterate_records
    self.record = self._next_record(self.next_line)
  File "/home/prateek/.local/lib/python3.6/site-packages/warcio/archiveiterator.py", line 262, in _next_record
    self.check_digests)
  File "/home/prateek/.local/lib/python3.6/site-packages/warcio/recordloader.py", line 88, in parse_record_stream
    known_format))
  File "/home/prateek/.local/lib/python3.6/site-packages/warcio/recordloader.py", line 243, in _detect_type_load_headers
    raise ArchiveLoadFailed(msg + str(se.statusline))
warcio.exceptions.ArchiveLoadFailed: Unknown archive format, first line: ['<?xml', 'version="1.0"', 'encoding="UTF-8"?>']

```
i am new to NewsPlease.
i have single python installed in my machine.
how can i resolve this issue.. thanks in advance..

**Versions (please complete the following information):**
 - OS: [ubuntu 18.04]
 - Python Version [ 3.6]
 - news-please Version [ 1.5.3]

**Comment by sara-02** [comment]
Hey @PRV0508 Can you please share the date range you are using and the places where you modified the code w.r.t date ranges.

**Comment by sara-02** [comment]
Also changes in the configurations you made, is the simple initial setup working as expected on your system?

**Comment by PRV0508** [comment]
```
############ YOUR CONFIG ############
# download dir for warc files
my_local_download_dir_warc = './cc_download_warc/'
# download dir for articles
my_local_download_dir_article = './cc_download_articles/'
# hosts (if None or empty list, any host is OK)
my_filter_valid_hosts = []  # example: ['elrancaguino.cl']
# start date (if None, any date is OK as start date), as datetime
my_filter_start_date =datetime.datetime(2020, 5, 1)
# end date (if None, any date is OK as end date), as datetime
my_filter_end_date =  datetime.datetime(2020, 5, 5)
# if date filtering is strict and news-please could not detect the date of an article, the article will be discarded
my_warc_files_start_date =  datetime.datetime(2020, 5, 1)
my_filter_strict_date = True
# if True, the script checks whether a file has been downloaded already and uses that file instead of downloading
# again. Note that there is no check whether the file has been downloaded completely or is valid!
my_reuse_previously_downloaded_files = True
# continue after error
my_continue_after_error = True
# show the progress of downloading the WARC files
my_show_download_progress = False
# log_level
my_log_level = logging.INFO
# json export style
my_json_export_style = 1  # 0 (minimize), 1 (pretty)
# number of extraction processes
my_number_of_extraction_processes = 2
# if True, the WARC file will be deleted after all articles have been extracted from it
my_delete_warc_after_extraction = True
# if True, will continue extraction from the latest fully downloaded but not fully extracted WARC files and then
# crawling new WARC files. This assumes that the filter criteria have not been changed since the previous run!
my_continue_process = True
############ END YOUR CONFIG #########
```
i am bit confusued about the exact file which is suppose to have these configurations.  currently these configurations are in commoncrawl.py.  i have not mady any changes in code except the configurations param **my_filter_start_ date** and  **my_filter_end_data**.
i am attaching all the commoncrawl files here.
yeah i am still try to run initial setup  but getting this error.
you can check all three files here. i have not edited any file yet. i am try to set it up as given here on github later then i'll change code according to my requirements. 
[google group link](https://groups.google.com/g/common-crawl/c/pzlr-OTytf8)

**Comment by PRV0508** [comment]
hey @sara-02 Can you please share the code which downloads warc files from the warc index. this current code is downloading an [this xml file](https://commoncrawl.s3.amazonaws.com/?prefix=crawl-data/CC-NEWS) which is actually an index of warc files. that's why it throws the warcio exception just because of warc parser is not getting a warc file to parse.

**Comment by sara-02** [comment]
hey @PRV0508 Here is the branch I used back then to help setup
https://github.com/sara-02/news-please/tree/run_on_lcs2_server
Have a look at the last 3 commits on this branch.
Although it is named server, I used this to run on local.

**Comment by sara-02** [comment]
Let me know if you need any more help. Also what dates are you running the setup for?

**Comment by PRV0508** [comment]
hey @sara-02  thanks for your support !
i am trying on same dates march 1st to 20th but facing the same error again. i have even tried the run your repo as well but getting same error. it is not downloading any warc file at all.  cc_download_warc directory contains a single file **https%3A%2F%2Fcommoncrawl.s3.amazonaws.com%2F** this file which is a xml document. this file seems to be an index file which contains url to individual doc but when if tried to download docs by the urls given in this index it gives this --
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>DE211B6C02E724C8</RequestId>
<HostId>vaQp4an25MXi51rSzU4xnDm4UBj9qwRe6EyBFLB1pvWSztmRms2Rvg9ug+kO5rnaQnmDtfbi9lg=</HostId>
</Error>

```
but actual link to the index is this [index file](https://commoncrawl.s3.amazonaws.com/?prefix=crawl-data/CC-NEWS/). this is index file which gives key to download the warc file and it works.
if we add suffix **2020/04** this  [index file](https://commoncrawl.s3.amazonaws.com/?prefix=crawl-data/CC-NEWS/2020/04) then it will an index file of april month's crawl news-data. 
how many warc file this **cc_download_warc** directory had when i run this locally setup ? in my case there is only file mention above.

**Comment by PRV0508** [comment]
hey @sara-02 thanks for your support !
i just find out that  all needed py library versions were letest. i just installed every library with exact same version that is mentioned in requirment.txt file. thanks you so much for timely support.

**Comment by Prateek-Tyagi** [comment]
hey @sara-02 
 i am trying to download and process data of 2-3 days only.
what changes should i make if i want to download warc file of a limited time duration ? i just need warc files from march 1st to 5th.  
changes i made ---
in common_crawler.py file
warc_files_start_date is (2020,3,1)
 warc_dates = __iterate_by_month(warc_files_start_date, datetime.datetime(2020,3,2))
confg.cfg and config_lib.cfg --
start_date = '2020-03-01 00:00:00'
end_date = '2020-03-02 00:00:00'

these changes does nothing and this still wants to download all the 400+ warc files of march month. due to limited resources i need very few files. what should i do for this ?

**Comment by sara-02** [comment]
@Prateek-Tyagi If you check this file here
https://github.com/sara-02/news-please/commit/a1edc4c914ec1775a4ac15fe36d14c68282ac88a
Then I have explicitly set a warc start and end date.

**Comment by sara-02** [comment]
See here by default, it D/Ws all warcs from the start date upto today!
https://github.com/fhamborg/news-please/blob/master/newsplease/crawler/commoncrawl_crawler.py#L125
So you one hack is to change the code and add your end date instead, the end date here should be one day greater than the last date you want to extract, like the python range thingy.

**Comment by Prateek-Tyagi** [comment]
i have change the code and added end date -  
[https://github.com/fhamborg/news-please/blob/master/newsplease/crawler/commoncrawl_crawler.py#L125](https://github.com/fhamborg/news-please/blob/master/newsplease/crawler/commoncrawl_crawler.py#L125)

`warc_dates = __iterate_by_month(warc_files_start_date, datetime.datetime(2020,3,3))`
is this right way to give end date ?
but -- 
```
my_local_download_dir_warc=./cc_download_warc/
my_local_download_dir_article=./cc_download_articles/
my_delete_warc_after_extraction=True
my_number_of_extraction_processes=60
INFO:newsplease.crawler.commoncrawl_crawler:-----DATE-------: 2020-03-01 00:00:00
INFO:newsplease.crawler.commoncrawl_crawler:executing: aws s3 ls --recursive s3://commoncrawl/crawl-data/CC-NEWS/2020/03/ --no-sign-request >> .tmpaws.txt && awk '{ print $4 }' .tmpaws.txt 
INFO:newsplease.crawler.commoncrawl_crawler:found 441 files at commoncrawl.org
INFO:newsplease.crawler.commoncrawl_crawler:creating extraction process pool with 60 processes        
```
look at it, still shows 441 files to download but this time duration has maximum of 6-7 warc files.
output does not show the end date as it is showing start date.
in your case did it downloaded all the warc files of march month or just till 20th march ?

**Comment by sara-02** [comment]
Yes, this should do.

**Comment by sara-02** [comment]
It downloaded a few extra as well, but extracted based dates.

**Comment by Prateek-Tyagi** [comment]
extraction works fine based on these dates but it downloads all 441 files .

**Comment by fhamborg** [comment]
closing this because the discussion is about the efficiency of the downloading process and not the initial error posted in the issue at first. please feel free to open a new issue for the latter, but there was already some discussion about this.
