### ISSUE TITLE
DateFilter not working when using CLI

### ISSUE THREAD

**Issue by beagle-barks** [fhamborg/news-please#177]
**Mandatory**
* [X] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [X] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

**Describe the bug**
I'm using news-please through the CLI, by simply calling `news-please`. In the `config.cfg` I've set the following information on the `DateFilter`section:

```
start_date = '2020-09-01 00:00:00'
end_date = '2021-09-01 00:00:00'
```

But it does not work somehow, there are still articles from 2003 for example.

**To Reproduce**
Replace the `start_date` and `end_date` in the config.cfg file when loading news-please via pip.

**Expected behavior**
There should only be articles from September 2020 to September 2021

**Versions (please complete the following information):**
 - macOS 10.15.6
 - Python Version: 3.8
 - news-please Version: latest version from pip as of 09/18/2020

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [x] business
* [ ] personal
* [ ] academic
* [ ] other

Thanks!

**Comment by alexdinisor98** [comment]
Hello. I have encountered the same issue. It seems like it is not filtered by date_publish, but rather by date_modify or date_download.
I am using this in **academic** purpose.
Thanks in advance!

**Comment by fhamborg** [comment]
you need to use the DateFilter module in the pipeline, as for example mentioned in the config file https://github.com/fhamborg/news-please/blob/328b2b9591ff53a22ff7ead1dd7b70bdc7cc3ee4/newsplease/config/config.cfg#L259

**Comment by nishalsach** [comment]
Hi, this still seems to be an issue (running with Python 3.8.10 in Google Colab). Also, just to clarify that I'm doing the right thing: when you say to "use the DateFilter module in the pipeline", do you mean changing the ```start_date```, ```end_date```, and ```strict_mode``` in ```config/config.cfg``` before calling news-please via the CLI? Doing that doesn't seem to help with the filtration and it still downloads everything. Is there a different way to call on the DateFilter module in the pipeline?
