### ISSUE TITLE
Tags keyword can't crawled

### ISSUE THREAD

**Issue by jugosx** [fhamborg/news-please#181]
**Mandatory**
* [x] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [x] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

Tags Keyword can't crawled from site.

**Comment by fhamborg** [comment]
what specifically do you mean by "tags keyword"?
