### ISSUE TITLE
awscli should be an optional dependency

### ISSUE THREAD

**Issue by rpocase** [fhamborg/news-please#182]
**Mandatory**
* [x] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [x] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one

**Describe the bug**
When trying to add news-please as a dependency to a poetry based repo, I ran into an issue where resolving the dependency graph was taking an extremely long time and needed some manual intervention. The issue had to do with resolving awscli historical dependencies.

**To Reproduce**
poetry add news-please

**Expected behavior**
The default news-please installation via pip or poetry does not include aws-cli. As far as I can tell, this is only needed for some sample scrapy spiders and not usage within the project's default path.

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [ ] personal
* [ ] academic
* [x] business
* [ ] other
* Some information on your project: N/A

**Comment by fhamborg** [comment]
Looking at which issues are reported in this repo, it seems that the path where awscli is required is currently the most frequently used path of newsplease (the common crawl news archive). Thus, I'll close this issue. THanks for the report! :)
