### ISSUE TITLE
May be this is a typo:  "import cchardet" instead of "import chardet"

### ISSUE THREAD

**Issue by parrondo** [fhamborg/news-please#189]
**Mandatory**
* [* ] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [* ] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

Related issues:
* add them here

**Describe the bug**
When you try to use news-please as a library you get an error message.

**To Reproduce**
With a new Google Colab notebook, the two cells following code is failing:

First cell:
 !pip3 install news-please

Second cell:
from newsplease import NewsPlease
article = NewsPlease.from_url('https://www.nytimes.com/2017/02/23/us/politics/cpac-stephen-bannon-reince-priebus.html?hp')
print(article.title)

**Expected behavior**
I expected to happen something like:

"Stephen Bannon Reassures Conservatives Uneasy About Trump"

**Log**
Add a log to help explain your problem, e.g., the full output of the tool that results from running the minimal working example you provided in `To Reproduce`.

---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-2-c60ac013243f> in <module>()
----> 1 from newsplease import NewsPlease
      2 article = NewsPlease.from_url('https://www.nytimes.com/2017/02/23/us/politics/cpac-stephen-bannon-reince-priebus.html?hp')
      3 print(article.title)

2 frames

/usr/local/lib/python3.6/dist-packages/newsplease/__init__.py in <module>()
     13 from dotmap import DotMap
     14 from newsplease.pipeline.pipelines import ExtractedInformationStorage
---> 15 from newsplease.crawler.simple_crawler import SimpleCrawler
     16 
     17 

/usr/local/lib/python3.6/dist-packages/newsplease/crawler/simple_crawler.py in <module>()
      7 import urllib3
      8 
----> 9 from .response_decoder import decode_response
     10 
     11 MAX_FILE_SIZE = 20000000

/usr/local/lib/python3.6/dist-packages/newsplease/crawler/response_decoder.py in <module>()
      2 import logging
      3 
----> 4 import cchardet  # For unknown encoding, see https://charset-normalizer.readthedocs.io/en/latest/ for more info
      5 
      6 LOGGER = logging.getLogger(__name__)

ModuleNotFoundError: No module named 'cchardet'

**Versions (please complete the following information):**
 - OS: [e.g. MacOS 10.2] Standard Google Colaboratory notebook (so, Ubuntu)
 - Python Version [e.g. 3.6] 3.6.9 (default, Oct  8 2020, 12:12:24) 
 - news-please Version [e.g. 1.2] pypi 1.5.13

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [ ] personal
* [ *] academic
* [ ] business
* [ ] other
* Some information on your project:

**Comment by lgov** [comment]
cchardet is the actual name of the package, not a typo. You'll need to install it on your machine:

https://pypi.org/project/cchardet/

I have never used Google Colab, but this should work in your notebook:
%pip install cchardet

**Comment by lodenrogue** [comment]
You should put this in the readme
