### ISSUE TITLE
Commoncrawl.py example NameError

### ISSUE THREAD

**Issue by keimiii** [fhamborg/news-please#206]
**Mandatory**
* [x] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [x] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

**Describe the bug**
A clear and concise description of what the bug is. This must include a full stack-trace (if applicable).

**To Reproduce**
python -m newsplease.examples.commoncrawl

**Expected behavior**
Crawled files to go to './cc_download_warc/' and './cc_download_articles/'

**Log**
Traceback (most recent call last):
  File "C:\Users\leong\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\leong\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\leong\git_environment\news-please\newsplease\examples\commoncrawl.py", line 38, in <module>
    from ..crawler import commoncrawl_crawler as commoncrawl_crawler
  File "C:\Users\leong\git_environment\news-please\newsplease\crawler\commoncrawl_crawler.py", line 236, in <module>
    fetch_images=fetch_images):
NameError: name 'fetch_images' is not defined

**Versions (please complete the following information):**
 - OS: Windows 10.0.19041 N/A Build 19041
 - Python Version: Python 3.8.5
 - news-please Version 1.5.17

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [ ] personal
* [ ] academic
* [x] business
* [ ] other
* Some information on your project: 
Testing how to use newsplease to query from the Common Crawl database

**Comment by fhamborg** [comment]
you can update news-please using pip or by cloning the repo and the issue should be fixed now
