### ISSUE TITLE
Bypass Paywall with credentials

### ISSUE THREAD

**Issue by maxschaeufele** [fhamborg/news-please#208]
Is there a built in feature with which I can log in to a news site to bypass the paywall? 
E.g. handelsblatt.com puts up a paywall after 3-4 read articles. This is reflected in the results when I try to scrape the articles of an RSS Feed.
I'm using news-please in lib mode in a Python project.

- OS: Windows 10
- Python Version 3.8
- news-please Version 1.5.18

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [x] personal
* [ ] academic
* [(x)] business
* [ ] other
* Some information on your project:

**Comment by fhamborg** [comment]
not possible unfortunately, since there is no common paywall "scheme" and np is a generic tool
