### ISSUE TITLE
cannot get related maintext

### ISSUE THREAD

**Issue by FaRzad-845** [fhamborg/news-please#215]
**Describe the bug**
When I receive information from a site like the one below, it cannot recognize the main part of the text ....

http://www.jahannews.com/news/769201

**To Reproduce**
```
from newsplease import NewsPlease
url = "http://www.jahannews.com/news/769201"
article = NewsPlease.from_url(url)
print(article.maintext)
```

**Log**
Return None

**Versions:**
 - OS: Linux Ubuntu 20.04
 - Python Version 3.6
 - news-please Version latest

**Intent**
* [x] personal
* [x] academic

**Comment by fhamborg** [comment]
Since np is intended to be a universal crawler, we expect that it does not work perfectly (or even at all as in this case) for all sites.
