### ISSUE TITLE
Download article does not complete

### ISSUE THREAD

**Issue by mdmadhu** [fhamborg/news-please#22]
When I try to download an article, my query 

> `newsplease.NewsPlease.download_article('http://www.thehindu.com/todays-p
   ...: aper/tp-national/tp-otherstates/Elephant-destroys-three-houses-in-Meghal
   ...: aya-village/article17026523.ece')`

does not complete or time-out on Python 3.5.2. On Python 2.7.3, however, it returns a result, but also returns the following TypeError

> `Traceback (most recent call last):
  File "/Users/mdmadhusudan/anaconda/envs/earthengine/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/mdmadhusudan/anaconda/envs/earthengine/lib/python2.7/site-packages/newsplease/pipeline/pipelines.py", line 365, in process_item
    json.dump(ExtractedInformationStorage.extract_relevant_info(item), file_)
TypeError: unbound method extract_relevant_info() must be called with ExtractedInformationStorage instance as first argument (got NewscrawlerItem instance instead)`

I am on macOS Sierra. Any suggestions on how to fix either? Thanks.

**Comment by fhamborg** [comment]
Should be fixed now in both versions (Py2.7 and 3.x). I also packaged the new code to PyPI so that you can simply perform `pip install news-please --upgrade`. Please let me know if this does work for you.

**Comment by mdmadhu** [comment]
Thanks, Felix! Confirming that the upgrade fixes this issue on Python 3.5.2.
