### ISSUE TITLE
news-please at background

### ISSUE THREAD

**Issue by noerarief23** [fhamborg/news-please#231]
**Mandatory**
* [x] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [x] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

**Describe your question**
Any Recomendation to running news-please at background? nohup?

**Versions (please complete the following information):**
 - OS: MacOS 12.4
 - Python Version: 3.10
 - news-please Version : latest

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [x] personal
* [x] academic
* [x] business
* [x] other
* Some information on your project:

**Comment by fhamborg** [comment]
yea i would also recommend one of the following

* nohup
* supervisord
