### ISSUE TITLE
ModuleNotFoundError: No module named 'newsplease'

### ISSUE THREAD

**Issue by dexeey** [fhamborg/news-please#235]
**Mandatory**
* [x] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [x] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

Related issues:
* add them here

**Describe your question**
How do I resolve this ModuleNotFound error?
![image](https://user-images.githubusercontent.com/80825816/197374494-6b1df5c3-72b7-4a2e-99d1-4e7c26de4e28.png)

**Versions (please complete the following information):**
 - OS: Window 10 21H2
 - Python Version: 3.9
 - news-please Version: 1.5.22

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [x] personal
* [ ] academic
* [ ] business
* [ ] other
* Some information on your project:

**Comment by fhamborg** [comment]
cant reproduce, looks like you didnt install news-please in the first place.
