### ISSUE TITLE
Get only the recursive list of URLs using the Library mode

### ISSUE THREAD

**Issue by bakrianoo** [fhamborg/news-please#236]
**Describe your question**

If I only interested in the list of discovered Recursive list of URLs of a website, what can I perform this from the library mode, so I can feed only the website URL, to get the list of discovered news URLs there. ?

I need to perform this from Python code (Library mode)

**Versions (please complete the following information):**
 - Python Version [3.7]

**Intent**
[*] academic

**Comment by fhamborg** [comment]
retrieving all links in the library mode is not supported currently. feel free to open a PR regarding this functionality :)
