### ISSUE TITLE
DateFilter is never used

### ISSUE THREAD

**Issue by namlede** [fhamborg/news-please#238]
**Mandatory**
* [ x ] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [ x ] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.
* [ x ] I confirm that this bug report does not report on a specific news site where news-please does not work. Please keep in mind that news-please is a generic crawler so it is expected that it will not work for all sites well or even at all. 

Related issues:
* https://github.com/fhamborg/news-please/issues/177
* https://github.com/fhamborg/news-please/issues/176

**Describe the bug**
change the config.cfg file to have:
start_date = '2023-01-01 00:00:00'

run news-please on the cli. The articles that we get are the same if this change does not happen. 
Note that the class DateFilter is not used anywhere in the code. Perhaps it was deleted by accident in some old merge.

**Versions (please complete the following information):**
 - OS: MacOS 12.6.2
 - Python 3.10.6
 - news-please 1.5.22

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [ ] personal
* [ x ] academic
* [ ] business
* [ ] other
* Some information on your project:

**Comment by GalKaplun** [comment]
Had the same issue.

**Comment by fhamborg** [comment]
As noted in the config.cfg "If added to the pipeline", you will need to add the DateFilter to the pipeline

**Comment by fhamborg** [comment]
see here
```# Pipeline activation
# Syntax: '<relative location>.<Pipeline name>': <Order of execution from 0-1000>
# default: {'newsplease.pipeline.pipelines.ArticleMasterExtractor':100, 'newsplease.crawler.pipeline.HtmlFileStorage':200, 'newsplease.pipeline.pipelines.JsonFileStorage': 300}
# Further options: 'newsplease.pipeline.pipelines.ElasticsearchStorage': 350
ITEM_PIPELINES = {'newsplease.pipeline.pipelines.ArticleMasterExtractor':100,
                  'newsplease.pipeline.pipelines.HtmlFileStorage':200,
                  'newsplease.pipeline.pipelines.JsonFileStorage':300
                  }
```

**Comment by cogentcoder** [comment]
I have exactly the same issue though I have already put the DateFilter in the Pipeline after ArticleMasterExtractor and gave the priority of 200, changing the downstream priority accordingly. but I have noticed that this filter works for some websites but not for others. Can you confirm if this is expected behavior or website filtering based on the DateFilter is strict one, meaning it has to filter it. 

Sorry to add this question to the closed issue. I think, it is better to open a new issue than to ask a question here.

**Comment by fhamborg** [comment]
This can be expected, e.g., if newsplease cannot figure out the date of an article, by default it will let the article pass through the datefilter. IIRC (havent used this feature in a while) theres a strict setting for the datefilter to control this behavior.

**Comment by liyucheng09** [comment]
@fhamborg Could you give an example of how to add datefilter to pipeline?
I have this in my config file, but it doesn't work. and I found no any instruction about it in the document.
```
ITEM_PIPELINES = {'newsplease.pipeline.pipelines.ArticleMasterExtractor':100,
                  'newsplease.pipeline.pipelines.DateFilter': 300,
                  'newsplease.pipeline.pipelines.HtmlFileStorage':200,
                  'newsplease.pipeline.pipelines.JsonFileStorage':300
                  }
```

**Comment by fhamborg** [comment]
I guess this should work
```
ITEM_PIPELINES = {'newsplease.pipeline.pipelines.ArticleMasterExtractor':100,
                  'newsplease.pipeline.pipelines.DateFilter': 150,
                  'newsplease.pipeline.pipelines.HtmlFileStorage':200,
                  'newsplease.pipeline.pipelines.JsonFileStorage':300
                  }

```
