### ISSUE TITLE
Specify more recent awscli dependency to avoid dependency resolution issues

### ISSUE THREAD

**Issue by phoerious** [fhamborg/news-please#239]
**Mandatory**
* [x] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [x] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.
* [x] I confirm that this bug report does not report on a specific news site where news-please does not work. Please keep in mind that news-please is a generic crawler so it is expected that it will not work for all sites well or even at all. 

Related issues:
* #182

**Describe the bug**
news-please depends on `awscli>=1.11.117`, but versions this old have broken metadata on PyPi. Using a package manager that tries to resolve dependencies (such as Poetry) will therefore have to download and inspect every single awscli version that has been published since about 2017. My last `poetry lock` took 3.5 hours. This issue can be fixed by simply depending on a more recent version (no earlier than October 2021, see https://github.com/aws/aws-cli/issues/5701).

I would suggest to simply depend on the most recent at the time, i.e., `awscli>=1.27.78`.

**Comment by fhamborg** [comment]
Does this have any side effects, e.g., the more recent awscli version having dependency conflicts with NP?

**Comment by phoerious** [comment]
Not I know of.

**Comment by phoerious** [comment]
Looks like this was removed a while ago. https://github.com/fhamborg/news-please/commit/14d0a20857e1ca0c65c63596ad629d6fd4262a2d

**Comment by fhamborg** [comment]
alright, thanks for the info

**Comment by fhamborg** [comment]
though, im wondering, why you ran into this issue. you opened the bug report in 2023 whereas the awscli was already removed in 2022. is this somehow still an issue or you just used an older version?

**Comment by phoerious** [comment]
Yeah, I believe that's the problem. Although that commit is older than my issue report, the latest version available on PyPi at the time was 1.5.22, which is from 4 April 2022 (18 days before that commit). The first version to include the fix must be 1.5.33, which is from 17 April 2023.

**Comment by fhamborg** [comment]
Alright, thanks for the clarification!!
