### ISSUE TITLE
Use this as a Python library

### ISSUE THREAD

**Issue by somnathrakshit** [fhamborg/news-please#24]
How can I use news-please in my code as a Python library? I would like to use this to crawl a list of sites continuously stored in a file.

**Comment by fhamborg** [comment]
If you want to crawl articles continuously, you need to run news-please in the CLI mode. Therefore, follow the documentation to add your sites to the sitelist.hjson (and enable RSS mode for each of them), see https://github.com/fhamborg/news-please/wiki/user-guide#markdown-header-add-own-urls
