### ISSUE TITLE
Change Crawlers to RecursiveCrawler with as a library and store to Mongodb 

### ISSUE THREAD

**Issue by Anhduchb01** [fhamborg/news-please#251]
**Describe your question**
How can i Change Crawlers to RecursiveCrawler with as a library ? 
And if i using via the CLI How can i store data news to Mongodb ? 

**Versions (please complete the following information):**
 - OS: [Window]
 - Python Version [3.9.16]
 - news-please Version [1.5.33]

**Comment by fhamborg** [comment]
Please use the template for bug reports, thanks.
