### ISSUE TITLE
can not extract main text.

### ISSUE THREAD

**Issue by simplew2011** [fhamborg/news-please#253]
**Describe the bug**
![image](https://github.com/fhamborg/news-please/assets/66729924/854f67c6-db5b-48a1-872e-bb4825748858)

**To Reproduce**
```
from newsplease import NewsPlease
article = NewsPlease.from_url('http://www.news.cn/world/2023-10/29/c_1212295036.htm')
print(article)
aa = article.get_serializable_dict()
print(aa)
exit()
```

can not extract main text.

**Comment by fhamborg** [comment]
not using bug report template, closing
