### ISSUE TITLE
Reuter news scrip failed 

### ISSUE THREAD

**Issue by pepingreat** [fhamborg/news-please#258]
I want to scrip Reuter news with an url (https://www.reuters.com/business/finance/morgan-stanley-opens-abu-dhabi-office-expanding-gulf-presence-2024-02-29/), 

but get the following mistakes:

home@mac-2 intlsts % /usr/local/bin/python3 "newsscraper.py"

not a 200 response: 401

Traceback (most recent call last):
  File "/Users/home/Library/Mobile Documents/com~apple~CloudDocs/WF/intlsts/newsscraper.py", line 3, in <module>
    print(article.maintext)
          ^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'maintext'

what could be the reason for this mistake, for other url, it works perfectly , but not Reuters

**Comment by fhamborg** [comment]
Please use the template for bug reports, thanks.
