### ISSUE TITLE
ImportError: libpq.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Pasanlaksitha** [fhamborg/news-please#259]
**Mandatory**
* [x] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [x] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

Related issues:
* add them here

**Describe your question**
after i run this code 

```python
from newsplease import NewsPlease
article = NewsPlease.from_url('https://www.nytimes.com/2017/02/23/us/politics/cpac-stephen-bannon-reince-priebus.html?hp')
print(article.title)
```

it gives this error 

```
Traceback (most recent call last):
  File "/home/zoro/.local/bin/news-please", line 5, in <module>
    from newsplease.__main__ import main
  File "/home/zoro/.local/lib/python3.9/site-packages/newsplease/__init__.py", line 15, in <module>
    from newsplease.pipeline.pipelines import ExtractedInformationStorage
  File "/home/zoro/.local/lib/python3.9/site-packages/newsplease/pipeline/pipelines.py", line 12, in <module>
    import psycopg2
  File "/home/zoro/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: libpq.so.5: cannot open shared object file: No such file or directory

```

**Versions (please complete the following information):**
 - OS: Linux amrv7
 - Python Version 3.9
 - news-please Version latest

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [] personal
* [x] academic
* [x] business
* [x] other
* Some information on your project: 
Train a  model

**Comment by fhamborg** [comment]
Issue is related to psycopg2, please open there
