### ISSUE TITLE
Unable to change URLS from example URLS

### ISSUE THREAD

**Issue by rinaforristal** [fhamborg/news-please#260]
**Mandatory**
* [X ] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [X ] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

Related issues:
Not important but when I add my own URL in the library version, in the same format as the example URL, I get the error about the dictionary. 

**Describe your question**
When I try to run newsplease by typing news-please in my terminal, it goes ahead and scrapes all the information from faz.net. From what I can tell, it goes on forever. I've tried replacing the example URLS with the ones I would like to see, but it still only searches on faz.net. I have even created a new json file and added my URLS in the format, then specified that file  in url_input_file_name in the config file. 
**Versions (please complete the following information):**
 - OS: Windows 10
 - Python Version [3.11.5
 - news-please Version latest cloned repository from github

**Intent (optional; we'll use this info to prioritize upcoming tasks to work on)**
* [ ] personal
* [ ] academic
* [x ] business
* [ ] other
* Some information on your project: 
I want to scan th efollowing websites and more:  https://www.bcbid.gov.bc.ca/page.aspx/en/usr/login?ReturnUrl=%2fpage.aspx%2fen%2fbuy%2fhomepage
https://www.merx.com/
https://www.bidsandtenders.com/suppliers/bid-opportunities/

**Comment by fhamborg** [comment]
Hi, I cannot reproduce your issue. I guess one reason why NP nevertheless only crawls from faz.net might be that you maybe edited the wrong file? Because the URL faz.net is nowhere hardcoded in NP's code, so if NP still crawls from that, my currently only assumption would be that the file it uses is another one than the one you edited.

**Comment by vinaygosain** [comment]
I also faced the same issue, but changing line 
```config_directory_default_path = "~/news-please-repo/config/"```
in __main__.py solved my issue
