### ISSUE TITLE
typing_extensions missing in requirements

### ISSUE THREAD

**Issue by t1h0** [fhamborg/news-please#275]
8e95c7180c97db2ed007eb1f6e2571b91a594dd3 added usage of typing_extensions to pipeline.py. Specifically, `cast()` is used which is only available in typing_extensions>=4.7.0. As typing_extensions is not a requirement to news-please, the solution to the issue is one of the following pull requests:

- #276: Adding typing_extensions>=4.7.0 as a requirement, however necessarily also raising the python version to 3.7+

or

- #277: Removing the usage of cast (as it is for type checking only and not needed anyway as far as I can tell)

**EDIT:** Newspaper4k (required by news-please) runs on python 3.8+. news-please should therefore be raised to 3.8 anyway so the first solution might be the best one.

**Comment by fhamborg** [comment]
thanks! fixed it with the help of your changes from #276
