### ISSUE TITLE
News please stopping in AWS EC2

### ISSUE THREAD

**Issue by perfecxus** [fhamborg/news-please#32]
In a AWS Ec2 instance with Ubuntu t2.micro instance, I have setup news-please to test if news-please works properly or not. But whenever, I am starting news-please, its failing giving  error "Unhandled error in Deferred:".

I tried starting in DEBUG mode also. I am attaching the stacktrace over here:
_

> /usr/local/lib/python3.5/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.13.1) or chardet (2.3.0) doesn't match a supported version!
>   RequestsDependencyWarning)
> [newsplease.config:165|INFO] Loading config-file (/home/ubuntu/news-please-repo/config/config.cfg)
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Crawler] default
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Files] url_input_file_name
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Files] working_path
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Files] local_data_directory
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [MySQL] host
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Elasticsearch] host
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Elasticsearch] ca_cert_path
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Elasticsearch] client_cert_path
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Elasticsearch] client_key_path
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] log_level
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] log_format
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] log_dateformat
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] log_encoding
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] jobdirname
> [newsplease.config:267|DEBUG] Loading JSON-file (/home/ubuntu/news-please-repo/config/sitelist.hjson)
> [newsplease.__main__:255|DEBUG] Calling Process: ['/usr/bin/python3', '/usr/local/lib/python3.5/dist-packages/newsplease/single_crawler.py', '/home/ubuntu/news-please-repo/config/config.cfg', '/home/ubuntu/news-please-repo/config/sitelist.hjson', '0', 'False', 'False']
> [newsplease.__main__:255|DEBUG] Calling Process: ['/usr/bin/python3', '/usr/local/lib/python3.5/dist-packages/newsplease/single_crawler.py', '/home/ubuntu/news-please-repo/config/config.cfg', '/home/ubuntu/news-please-repo/config/sitelist.hjson', '1', 'False', 'False']
> [newsplease.__main__:255|DEBUG] Calling Process: ['/usr/bin/python3', '/usr/local/lib/python3.5/dist-packages/newsplease/single_crawler.py', '/home/ubuntu/news-please-repo/config/config.cfg', '/home/ubuntu/news-please-repo/config/sitelist.hjson', '2', 'False', 'False']
> /usr/local/lib/python3.5/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.13.1) or chardet (2.3.0) doesn't match a supported version!
>   RequestsDependencyWarning)
> /usr/local/lib/python3.5/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.13.1) or chardet (2.3.0) doesn't match a supported version!
>   RequestsDependencyWarning)
> /usr/local/lib/python3.5/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.13.1) or chardet (2.3.0) doesn't match a supported version!
>   RequestsDependencyWarning)
> [newsplease.config:165|INFO] Loading config-file (/home/ubuntu/news-please-repo/config/config.cfg)
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Crawler] default
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Files] url_input_file_name
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Files] working_path
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Files] local_data_directory
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [MySQL] host
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Elasticsearch] host
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Elasticsearch] ca_cert_path
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Elasticsearch] client_cert_path
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Elasticsearch] client_key_path
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] log_level
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] log_format
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] log_dateformat
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] log_encoding
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] jobdirname
> [__main__:88|DEBUG] Config initialized - Further initialisation.
> [newsplease.config:267|DEBUG] Loading JSON-file (/home/ubuntu/news-please-repo/config/sitelist.hjson)
> [newsplease.config:165|INFO] Loading config-file (/home/ubuntu/news-please-repo/config/config.cfg)
> [__main__:192|DEBUG] Using crawler RecursiveCrawler for https://www.dig-in.com/.
> [__main__:253|INFO] Removed /home/ubuntu/news-please-repo/.resume_jobdir/55ae9ff89e530b083b20633a558d116b since '--resume' was not passed to initial.py or this crawler was daemonized.
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Crawler] default
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Files] url_input_file_name
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Files] working_path
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Files] local_data_directory
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [MySQL] host
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Elasticsearch] host
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Elasticsearch] ca_cert_path
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Elasticsearch] client_cert_path
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Elasticsearch] client_key_path
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] log_level
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] log_format
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] log_dateformat
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] log_encoding
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] jobdirname
> [__main__:88|DEBUG] Config initialized - Further initialisation.
> [newsplease.config:267|DEBUG] Loading JSON-file (/home/ubuntu/news-please-repo/config/sitelist.hjson)
> [newsplease.config:165|INFO] Loading config-file (/home/ubuntu/news-please-repo/config/config.cfg)
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Crawler] default
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Files] url_input_file_name
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Files] working_path
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Files] local_data_directory
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [MySQL] host
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Elasticsearch] host
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Elasticsearch] ca_cert_path
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Elasticsearch] client_cert_path
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Elasticsearch] client_key_path
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] log_level
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] log_format
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] log_dateformat
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] log_encoding
> [newsplease.config:167|DEBUG] Option not literal_eval-parsable (maybe string): [Scrapy] jobdirname
> [__main__:88|DEBUG] Config initialized - Further initialisation.
> [newsplease.config:267|DEBUG] Loading JSON-file (/home/ubuntu/news-please-repo/config/sitelist.hjson)
> [__main__:192|DEBUG] Using crawler RecursiveCrawler for http://www.insurancejournal.com/.
> [__main__:253|INFO] Removed /home/ubuntu/news-please-repo/.resume_jobdir/8294b9c2cc3db1cadb6b4a98109c8590 since '--resume' was not passed to initial.py or this crawler was daemonized.
> [__main__:192|DEBUG] Using crawler RecursiveCrawler for http://www.dnaindia.com/.
> [__main__:253|INFO] Removed /home/ubuntu/news-please-repo/.resume_jobdir/6906ed0b1a6ca7bd359e919a4fd74596 since '--resume' was not passed to initial.py or this crawler was daemonized.
> Unhandled error in Deferred:
> 
> Unhandled error in Deferred:
> 
> Unhandled error in Deferred:
> 
> [newsplease.__main__:270|INFO] Graceful stop called manually. Shutting down.

_

Please help.

**Comment by fhamborg** [comment]
I've seen the error `Unhandled error in Deferred` multiple times and it was always related to a dependency issue. Which version of news-please are you using? 

Your log contains several warnings about using an unspported version, e.g, `/usr/local/lib/python3.5/dist-packages/requests/init.py:80: RequestsDependencyWarning: urllib3 (1.13.1) or chardet (2.3.0) doesn't match a supported version!
RequestsDependencyWarning)` Are you testing news-please on a fresh machine?

**Comment by fhamborg** [comment]
I'm closing this issue, feel free to reopen in case the issue remains.
