### ISSUE TITLE
HTTP Error 505: HTTP Version not supported

### ISSUE THREAD

**Issue by Zombo1296** [fhamborg/news-please#36]
Hi, 
I try to getting started by running commoncrawl.py but encountered this error. I checked everything I know but still no luck. Do you happen to know what this issue is about? Attached is the error log. 
[errorlog.txt](https://github.com/fhamborg/news-please/files/1219321/errorlog.txt)

Thank you for your time.

**Comment by fhamborg** [comment]
Hi,
you need to install the aws cli at first. That is currently missing from the script, I guess I need to add some instructions regarding that. You can simply install the aws cli with pip
```
pip3 install awscli
```

Feel free to reopen this issue in case the problem persists
