### ISSUE TITLE
run news-please in a cluster

### ISSUE THREAD

**Issue by dustyny** [fhamborg/news-please#37]
News-please has been very easy to setup & test. I've been getting excellent results during my testing, now I'm considering putting it in to production. 

I'm trying to figure out the best way to run multiple instances in an AWS ECS cluster. If multiple News-please crawlers point to the same MySQL database, will this allow them to distribute the tasks across a cluster? 

If not; do you have any thoughts on how to run news-please in a scalable cluster?

**Comment by fhamborg** [comment]
I'm assuming you're planning to run news-please in CLI mode, since you mentioned storing to MySQL DB. When designing news-please, running it in parallel was one of the design requirements so that should actually work but we've never tested it yet.

You should be able to run news-please in parallel by setting up a different `sitelist.hjson` file on each of the instances: each instance would deal with a different subset of all the sites that you're planning to crawl. The `config.cfg` file would be the same on all of them.

**Comment by dustyny** [comment]
Yes I am planning on running it in CLI mode. I'll see if I can get it to work in a AWS container cluster and report back my results. I have a few questions before I start. 

When I restart the docker containers any local files will be destroyed. Am I correct that this should not be a problem because the crawl history is persisted to MySQL? 

You're suggesting that I segment my crawlers by domain. In this case each node will have a unique sitelist.hjson. 
**Example:** 
Node-1
1. Publication_1.com
2. Publication_2.com
Node-2
1.  Publication_3.com
2.  Publication_4.com
Node-3
1.  Publication_5.com
2.  Publication_6.com

Is it possible to use subdomains and path in the hjson? 
**Example:** 
Node-1
1. publication_1.com
2. news.publication_2.com
Node-2
1.  publication_1.com/sports
2.  publication_3.com
Node-3
1.  fashion.publication_2.com
2.  publication_4.com

**Comment by fhamborg** [comment]
> When I restart the docker containers any local files will be destroyed. Am I correct that this should not be a problem because the crawl history is persisted to MySQL?
Yes.

> You're suggesting that I segment my crawlers by domain. In this case each node will have a unique sitelist.hjson.
Correct.

> Is it possible to use subdomains and path in the hjson?
Yes, but make sure to set `sitemap_allow_subdomains` to False in https://github.com/fhamborg/news-please/wiki/configuration

**Comment by fhamborg** [comment]
Closing this for now. Feel free to reopen in case any issues occurs or you wanna share your experience with the community. Thank you!

**Comment by dustyny** [comment]
Thank you. I'll let you know how it goes. I just have to workout another part of the pipeline first.
