### ISSUE TITLE
Error installing via pip under Windows

### ISSUE THREAD

**Issue by henninglebbaeus** [fhamborg/news-please#45]
I experienced a problem with the installation via pip under Windows 10 (64-bit) and Python 3.5.
```
Collecting pywin32>=220 (from news-please)
  Could not find a version that satisfies the requirement pywin32>=220 (from news-please) (from versions: )
No matching distribution found for pywin32>=220 (from news-please)
```
Is there a quick solution to this problem?

**Comment by fhamborg** [comment]
Does this help? https://stackoverflow.com/questions/40981120/python-pip-cannot-find-pywin32-on-windows ie install `pip3 install pypiwin32` Please let me know how you fixed the problem so that I can change the code correspondingly.

**Comment by henninglebbaeus** [comment]
I tried the proposed solution already. However, the same error came up during installation of news-please via pip. I guess changing the requirements.txt file helps. Looks like pip treats pypiwin32 and pywin32 as two different things when checking the requirements.

My quick fix: installed it in a python 2.7 environment 😊

**Comment by fhamborg** [comment]
so did manually installing pypiwin32 help? did you use pip install news-please or git clone and then run pip install -r requirements.txt

**Comment by henninglebbaeus** [comment]
No, manually installing pypiwin32 did not help for me. 

I used `pip install news-please`. Did not try cloning from git yet.

**Comment by fhamborg** [comment]
Alright, the issue seems to be that pywin32 does not support Python 3.4 and later, see also https://pypi.python.org/pypi/pywin32/214

I'm gonna close this issue, Python 3.4 and later on Windows will not be supported.

**Comment by berkeoral** [comment]
I had this issue for python 3.6 in Windows 10. Installing pywin32 solved the problem.

https://sourceforge.net/projects/pywin32/files/pywin32/Build%20221/
