### ISSUE TITLE
Error installing news-please

### ISSUE THREAD

**Issue by nithinkarthik6** [fhamborg/news-please#48]
C:\Users\nithi>pip3 install news-please
Collecting news-please
  Using cached news-please-1.2.35.tar.gz
Collecting Scrapy>=1.1.0 (from news-please)
  Using cached Scrapy-1.4.0-py2.py3-none-any.whl
Collecting PyMySQL>=0.7.9 (from news-please)
  Using cached PyMySQL-0.8.0-py2.py3-none-any.whl
Collecting hjson>=1.5.8 (from news-please)
  Using cached hjson-3.0.1.tar.gz
Collecting elasticsearch>=2.4 (from news-please)
  Using cached elasticsearch-6.0.0-py2.py3-none-any.whl
Collecting beautifulsoup4>=4.3.2 (from news-please)
  Using cached beautifulsoup4-4.6.0-py3-none-any.whl
Collecting readability-lxml>=0.6.2 (from news-please)
  Using cached readability-lxml-0.6.2.tar.gz
Collecting langdetect>=1.0.7 (from news-please)
  Using cached langdetect-1.0.7.zip
Collecting python-dateutil>=2.4.0 (from news-please)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting plac>=0.9.6 (from news-please)
  Using cached plac-0.9.6-py2.py3-none-any.whl
Collecting dotmap>=1.2.17 (from news-please)
  Using cached dotmap-1.2.20.tar.gz
Collecting PyDispatcher>=2.0.5 (from news-please)
  Using cached PyDispatcher-2.0.5.tar.gz
Collecting warcio>=1.3.3 (from news-please)
  Using cached warcio-1.5.1-py2.py3-none-any.whl
Collecting ago>=0.0.9 (from news-please)
  Using cached ago-0.0.92.tar.gz
Collecting six>=1.10.0 (from news-please)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting lxml>=3.3.5 (from news-please)
  Using cached lxml-4.1.1-cp36-cp36m-win32.whl
Collecting awscli>=1.11.117 (from news-please)
  Using cached awscli-1.14.16-py2.py3-none-any.whl
Collecting hurry.filesize>=0.9 (from news-please)
  Using cached hurry.filesize-0.9.tar.gz
Collecting newspaper3k (from news-please)
  Using cached newspaper3k-0.2.5.tar.gz
Collecting pywin32>=220 (from news-please)
  Could not find a version that satisfies the requirement pywin32>=220 (from news-please) (from versions: )
No matching distribution found for pywin32>=220 (from news-please)

C:\Users\nithi>pip install pypiwin32
Collecting pypiwin32
  Downloading pypiwin32-220-cp36-none-win32.whl (8.3MB)
    100% |████████████████████████████████| 8.3MB 69kB/s
Installing collected packages: pypiwin32
Successfully installed pypiwin32-220

C:\Users\nithi>pip3 install news-please
Collecting news-please
  Using cached news-please-1.2.35.tar.gz
Collecting Scrapy>=1.1.0 (from news-please)
  Using cached Scrapy-1.4.0-py2.py3-none-any.whl
Collecting PyMySQL>=0.7.9 (from news-please)
  Using cached PyMySQL-0.8.0-py2.py3-none-any.whl
Collecting hjson>=1.5.8 (from news-please)
  Using cached hjson-3.0.1.tar.gz
Collecting elasticsearch>=2.4 (from news-please)
  Using cached elasticsearch-6.0.0-py2.py3-none-any.whl
Collecting beautifulsoup4>=4.3.2 (from news-please)
  Using cached beautifulsoup4-4.6.0-py3-none-any.whl
Collecting readability-lxml>=0.6.2 (from news-please)
  Using cached readability-lxml-0.6.2.tar.gz
Collecting langdetect>=1.0.7 (from news-please)
  Using cached langdetect-1.0.7.zip
Collecting python-dateutil>=2.4.0 (from news-please)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting plac>=0.9.6 (from news-please)
  Using cached plac-0.9.6-py2.py3-none-any.whl
Collecting dotmap>=1.2.17 (from news-please)
  Using cached dotmap-1.2.20.tar.gz
Collecting PyDispatcher>=2.0.5 (from news-please)
  Using cached PyDispatcher-2.0.5.tar.gz
Collecting warcio>=1.3.3 (from news-please)
  Using cached warcio-1.5.1-py2.py3-none-any.whl
Collecting ago>=0.0.9 (from news-please)
  Using cached ago-0.0.92.tar.gz
Collecting six>=1.10.0 (from news-please)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting lxml>=3.3.5 (from news-please)
  Using cached lxml-4.1.1-cp36-cp36m-win32.whl
Collecting awscli>=1.11.117 (from news-please)
  Using cached awscli-1.14.16-py2.py3-none-any.whl
Collecting hurry.filesize>=0.9 (from news-please)
  Using cached hurry.filesize-0.9.tar.gz
Collecting newspaper3k (from news-please)
  Using cached newspaper3k-0.2.5.tar.gz
Collecting pywin32>=220 (from news-please)
  Could not find a version that satisfies the requirement pywin32>=220 (from news-please) (from versions: )
No matching distribution found for pywin32>=220 (from news-please)

**Comment by fhamborg** [comment]
https://github.com/fhamborg/news-please/issues/45
