### ISSUE TITLE
Timeout URL retrieval

### ISSUE THREAD

**Issue by sborms** [fhamborg/news-please#55]
Hi,

I wonder how to properly integrate a timeout for an URL retrieval? For example, below URL keeps on running on my machine (I'm on Windows in case useful):

```
url = 'http://www.nasdaq.com/article/forex-eurusd-keeps-pushing-higher-cm232206?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+nasdaq%2Fcategories+%28Articles+by+Category%29'
out = NewsPlease.from_url(url)
```

The problem is more general. I would like to say: try to retrieve this URL for at maximum N seconds, else quit.

I ran without success through the options outlined here: https://stackoverflow.com/questions/492519/timeout-on-a-function-call. The function just keeps running.

I couldn't find anything in the wiki, nor config file. Maybe I overlooked it. Hope somebody can help.

Many thanks,

Sam

**Comment by fhamborg** [comment]
I've added that functionality with the latest commit a2bc51210aaefc6f7a4afb8f72992a0919d99854
