### ISSUE TITLE
AttributeError: 'NewsArticle' object has no attribute 'publish_date'

### ISSUE THREAD

**Issue by tsoahans** [fhamborg/news-please#60]
The error has happened when I run the example code "commoncrawl.py".

This will cause the program to stop.

The bug is in the function [__get_publishing_date](https://github.com/fhamborg/news-please/blob/master/newsplease/crawler/commoncrawl_extractor.py#L136) in [commoncrawl_extractor.py.](https://github.com/fhamborg/news-please/blob/master/newsplease/crawler/commoncrawl_extractor.py)

It should be checked whether the attribute is existing before accessing "article.publish_date".

I don't know why did this bug happen, I just add
```python
if not hasattr(article, "publish_date"):
    return None
```
at the beginning of the function to prevent the program stopping.

**Comment by fhamborg** [comment]
you may get the fix by running `pip3 install -U news-please`
