### ISSUE TITLE
To str convertion of the datetime fields

### ISSUE THREAD

**Issue by Anastasu6ka** [fhamborg/news-please#61]
Hi, 

if a standard pipeline use implies using a get_dict method from NewsArticle class to convert a class instance to dict and then save it to json file, then the fields
            'date_download': self.date_download,
            'date_modify': self.date_modify,
            'date_publish': self.date_publish
need to be casted to string in the get_dict method. Otherwise there is a problem that datetime fields are not json serializable.

**Comment by fhamborg** [comment]
Serializing to JSON works well for instance in the common_crawl script. Can you please provide a minimal example where this does not work?

**Comment by Anastasu6ka** [comment]
It happens running simple downloadfromurl.py 

TypeError: Object of type 'NewsArticle' is not JSON serializable

The problem vanishes when: 
1) I change get_dict() method in NewsArticle with datetime conversion to string 
            'date_download': str(self.date_download),
            'date_modify': str(self.date_modify),
            'date_publish': str(self.date_publish),
2) save not an object, but it's dictionary 
            json.dump(article.get_dict(), outfile, indent=4, sort_keys=True)

If I save like you have in the commoncrawl example
            json.dump(article.__dict__, outfile, indent=4, sort_keys=True) 
I get this error: 
TypeError: Object of type 'datetime' is not JSON serializable

I run everything on 3.6.

**Comment by fhamborg** [comment]
if you add `default=str` to the json.dump method (see commoncrawl.py:102), this will solve the issue. but from a user perspective, it's better to have a get serializable dict method. will add that. thanks for pointing this out.

**Comment by boseshantanu** [comment]
@fhamborg Have you updated it in Git? I am still facing the same issue.

**Comment by boseshantanu** [comment]
I can't figure out where I am going wrong

import json
from newsplease import NewsPlease

url = 'testurl'
basepath = '/Volumes/Data/StartUp Data/NewsExtractor/Custom/ExtractedData'

article = NewsPlease.from_url(url)

with open(basepath + article['filename'] + '.json', 'w') as outfile:
    json.dump(article, outfile, indent=4, sort_keys=True)


Error:
Traceback (most recent call last):
  File "second.py", line 16, in <module>
    with open(basepath + article['filename'] + '.json', 'w') as outfile:
TypeError: 'NewsArticle' object is not subscriptable

**Comment by fhamborg** [comment]
this seems to be a different issue. note that your original issue contained "TypeError: Object of type 'datetime' is not JSON serializable", which was fixed using https://github.com/fhamborg/news-please/commit/93deacbab98bbabae28f13a30fc06e66ff2e4d3a. now you get "TypeError: 'NewsArticle' object is not subscriptable". please open a new issue for your new issue.
