### ISSUE TITLE
Remove optional dependencies from install_requires

### ISSUE THREAD

**Issue by henadzit** [fhamborg/news-please#70]
Hello,

First of all, thank you for a great piece of software!

I faced a dependency conflict when I tried to use the package. We're dependent on boto3==1.7.84 but news-please requires awscli which requires a newer version of botocore. I also think that there are lots of news-please users who don't need AWS-related functionality. What do you think about making some dependencies optional like awscli, PyMySQL, elasticsearch? If you support this, I can help with a PR.

Thanks,
Henadzi

**Comment by fhamborg** [comment]
a PR would be good! :-)

**Comment by fhamborg** [comment]
I'm gonna close this, please just send a PR if you want to fix this issue, or feel free to reopen the issue. Thanks!
