### ISSUE TITLE
Daemonize interval not respected?

### ISSUE THREAD

**Issue by abidibo** [fhamborg/news-please#72]
**Describe the bug**
I'm not sure this is a bug, maybe this is an expected behavior that I just can't grasp.
The daemonize interval is not respected when the app can crawl everything in time, one crawl operation every two is performed earlier.

**To Reproduce**
Start the cli application, with only 1 site in hjson list and a daemonize value of 60 seconds. Add some print statements to detect at what time the crawl is started. Look at those time intervals, they do not respect the right interval (60 seconds).

What happens is:

the [pajama time](https://github.com/fhamborg/news-please/blob/master/newsplease/__main__.py#L233) is the difference between the schedule time and now. When it is greater than 0 the thread is correctly delayed, but the popped item was already rescheduled at now + daemonize (even if it will not run now), so if for example the daemonize value is 60, and crawler does its job in 7 seconds, at the next loop the pajama_time is 53, the threads waits for 53 seconds and executes the crawler again, BUT after 7 seconds the crawler starts again! That’s because was programmed at now() + 60 when was popped out from the queue and before being delayed!

**Expected behavior**
If in time, the next execution should be scheduled always after daemonize seconds.

**Screenshots**
![screenshot from 2018-10-31 13-48-01](https://user-images.githubusercontent.com/444093/47790530-b5453c80-dd17-11e8-8236-7af3151cf002.png)

**Versions (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS
 - Python Version: 3.6
 - news-please: 1.2.36 (a fork of this release)

**Proposed solution**
If this is not the expected bahavior, maybe the following can fix the [get_next_item](https://github.com/fhamborg/news-please/blob/master/newsplease/__main__.py#L597) function:

	def get_next_item(self):
	    """
	    Gets the next daemon-item and adds the daemon to the queue again.
	    (With the new scheduled time)
	    """
	    if self.graceful_stop:
		return None
	    self.lock.acquire()
	    self.sort_queue()
	    try:
		item = self.queue.pop(0)
		prev_time = self.queue_times.pop(0)
		# prev + daemonize if in time, now + daemonize if in delay
		self.add_execution(
		    max(prev_time, time.time()) + self.daemons[item[1]], item[1]
		)
	    finally:
		self.lock.release()

	    return item

**Comment by fhamborg** [comment]
I'll look into this in more detail soon. The `get_next_item` method you posted and adapted is based on the `https://github.com/fhamborg/news-please/blob/master/newsplease/__main__.py#L597` method (in class DaemonList) right?
Thank you for the report.

**Comment by abidibo** [comment]
@fhamborg yes it is.
Of course, thanks for the amazing library!

**Comment by fhamborg** [comment]
@abidibo is there any particular reason you omitted the line `self.queue_times.pop(0)` from your updated code snippet? in the current code, that is line 608, but it's missing from your code snippet. other than that, I think your suggestion makes sense to add.

**Comment by abidibo** [comment]
@fhamborg I haven't omitted it, I've just assigned it to the variable `prev_time` that I use to calculate next occurrence if greater than now:

`prev_time = self.queue_times.pop(0)`

**Comment by fhamborg** [comment]
Oh, sorry, my fault, I've somehow managed to simply overlook that line.. I'll update the method to fix this issue. Thank you! :-)
