### ISSUE TITLE
Extract Keywords inside News Article in a News Website

### ISSUE THREAD

**Issue by blackopscompany** [fhamborg/news-please#78]
Hi guys...

Could you please help me to extract keywords in the News Article in a News Website using news-please?
I have a case to extract the keywords of all articles in a news website. That website is this one : https://news.detik.com/indeks. So that, i can monitor the keywords is being trending in that website.

Thank you

**Comment by fhamborg** [comment]
I'm sorry but thats beyond the focus of news-please.
