### ISSUE TITLE
http 406 error when using a url 

### ISSUE THREAD

**Issue by Akshit99** [fhamborg/news-please#80]
Hey! You have an awesome package and I love the simplicity it creates. I have an issue with a url of mine. So I'm extracting a set of url from google by searching a keyword. Now for all those urls, I need to get the content out of those. But for some urls, I'm getting a 406 NOT acceptable error.

raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 406: Not Acceptable

So How can i remove these url when I run this..
article = NewsPlease.from_url(url)
if statuscode == 200:
 (then i continue working)
How can i call this status code in from_url() function????

Thanks in advance!

**Comment by fhamborg** [comment]
Hi, this info is not exposed by the news-please API. You may check for an error though:
```
if not article:
   print("error")
else:
   print( article.title)
```
