### ISSUE TITLE
 [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by burf2000** [fhamborg/news-please#81]
**Describe the bug**
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>

**To Reproduce**
Run
```
from newsplease import NewsPlease
article = NewsPlease.from_url('https://www.bbc.co.uk/news/technology')
print(article.title)
```
**Expected behavior**
It to get me some news articles

**Versions (please complete the following information):**
OSX 10.13.6
Python 3.7

**Comment by fhamborg** [comment]
can you please paste the full console output?

**Comment by fhamborg** [comment]
the issue is related to urllib: https://stackoverflow.com/a/53310545
