### ISSUE TITLE
Possible to specify date format?

### ISSUE THREAD

**Issue by samrbrt** [fhamborg/news-please#83]
Is it possible to specify date format for date_publish when it is used as lib?

NewsPlease.from_url() returns a wrong date since it uses '%m %d %y' but some sites that I was trying to crawl returns in the format of  '%d %m %y' thus interchanging month's and date's values. Is there any way of specifying these while using the API?

**Comment by fhamborg** [comment]
you may need to adapt the code: news-please is using https://dateparser.readthedocs.io/en/latest/ which allows you to specify a date_formats list
