### ISSUE TITLE
How do i store text in mysql ? (mysql is working for me)

### ISSUE THREAD

**Issue by vrushangdev** [fhamborg/news-please#84]
how to add all data we get from news site's ,
can u share tutorial regarding that 🥇 .

**Comment by vrushangdev** [comment]
<img width="1680" alt="screenshot 2019-02-22 at 4 08 06 pm" src="https://user-images.githubusercontent.com/45510867/53237211-22f8e800-36bc-11e9-9854-eb2b9ce1b794.png">
<img width="1680" alt="screenshot 2019-02-22 at 4 08 15 pm" src="https://user-images.githubusercontent.com/45510867/53237212-22f8e800-36bc-11e9-9022-82305357a914.png">

**Comment by vrushangdev** [comment]
@fhamborg pls help to resolve it :)

**Comment by fhamborg** [comment]
Please read the documentation (as suggested in another ticket you created, #82) and until then refrain from opening tickets, thanks.
