### ISSUE TITLE
Issue #54

### ISSUE THREAD

**Issue by aamin3** [fhamborg/news-please#88]
Hello, i'm getting the same subscriptable TypeError as outlined in issue #54:
https://github.com/fhamborg/news-please/issues/54
 This is true for .from_url version as well, where there is only 1 URL and its not being pulled from a file:

url = 'https://www.cnn.com/2019/03/11/tech/elon-musk-deadline-sec/index.html'
basepath= '#redacted'

article = NewsPlease.from_url(url)

with open(basepath + article['filename'] + '.json', 'w') as outfile:
    json.dump(article, outfile, indent=4, sort_keys=True)

news-please works fine in both CLI and library mode as long as I don't try to create a JSON file

**Comment by w142857** [comment]
Hi there, how was your problem solved?

**Comment by camil0palacios** [comment]
try this:

with open(download_dir + article.filename + '.json', 'w') as outfile:
        json.dump(article.get_serializable_dict(), outfile, indent=4, sort_keys=True)

**Comment by camil0palacios** [comment]
try this:

with open(download_dir + article.filename + '.json', 'w') as outfile:
        json.dump(article.get_serializable_dict(), outfile, indent=4, sort_keys=True)

**Comment by peterkabz** [comment]
for me i used  
`dict_article=article.get_dict()
  file_name=dict_article["filename"]

`
