### ISSUE TITLE
postgres: implement all fields (can reuse from elasticsearch) and add doc for that in wiki

### ISSUE THREAD

**Issue by fhamborg** [fhamborg/news-please#9]

**Comment by andreierdoss** [comment]
Any plans to support Postgres?

**Comment by fhamborg** [comment]
most definitely, but we dont have resources available to implement this feature in the near future. would gladly accept PRs though including changes in the code, doc and tests

**Comment by andreierdoss** [comment]
I added the Postgresql Storage pipeline - https://github.com/fhamborg/news-please/pull/140, please take look

**Comment by fhamborg** [comment]
addressed by your PR, thank you!
