### ISSUE TITLE
Bad Encoding (Mix of Unicode Characters and Bytes) in from_warc

### ISSUE THREAD

**Issue by gursky1** [fhamborg/news-please#90]
So I am taking articles titles from the Common Crawl news WARC files using NewsPlease, but when I take the articles titles, but they are a mixture of normally encoded characters and Unicode bytes, and I am unable to get it encoded correctly. I have some the WARC files downloaded manually, and I using some of the code from the common_crawl_extractor() script to pull from them, specifically the `from_warc` method:

```
def check_warc(warc, hosts):
    url = warc.rec_headers.get_header('WARC-Target-URI')
    try:
        for i in hosts:
            if i in url:
                article = NewsPlease.from_warc(warc)
                return (True, article)
    except:
        return (False, None)
    return (False, None)

# Iterating over all specified files
for warc in warc_files:
    with open(warc, 'rb') as stream:
        for record in ArchiveIterator(stream):
            response = check_warc(record, good_hosts)
            if response[0]:
                articles.append(response[1])
                pulled_counter += 1
            total_counter += 1
            sys.stdout.write('\rArticles Pulled: '+str(pulled_counter)+' out of '+str(total_counter))
            sys.stdout.flush()
```

Taking one of the titles: (articles is a list of NewsPlease article objects).

`x = articles[1].title`

If I call x in spyder, it returns:

`'Las 10 canciones m\\xc3\\xa1s populares de la semana'`

When I use `print(x)` I get:

`Las 10 canciones m\xc3\xa1s populares de la semana`

BUT if try to correctly encode it using: (As other posts suggest on stackoverflow)

`x.encode('latin1').decode('utf8')`

It returns 

`'Las 10 canciones m\\xc3\\xa1s populares de la semana'`

Which is obviously not correct.

Also note I am using the pip installed version of NewsPlease and not the GitHub version.

**Comment by fhamborg** [comment]
This seems to be an issue not related to news-please but to encoding in general. Please note that we currently have only resources to fix bugs in news-please but unfortunately cannot give further support, e.g., on how to use it properly. However, if you think that this is an issue specific to news-please, feel free to reopen the issue and we'll gladly look into it. Thanks!
