### ISSUE TITLE
Not able to extract published date

### ISSUE THREAD

**Issue by tsoernes** [fhamborg/news-please#91]
**Describe the bug**
The `'date_publish'` field is `None` for all articles scraped with the default crawler (which I assume is the Sitemap crawler) on https://www.bankingtech.com (which does have a sitemap).

These articles (e.g. https://www.bankingtech.com/2019/03/pakitans-first-microfinance-bank-cuts-over-to-temenos-t24/) do have a publish date in them.

**To Reproduce**
Run `news-please` cli with default config, with a bare `sitelist` config containing just the main URL above

**Versions (please complete the following information):**
 - OS: Fedora 29
 - Python Version 3.7
 - news-please Version  1.2.44

**Comment by truenodeverano** [comment]
I'm having a similar issue...The date range on the config file is not restricting the articles that are being pulled.

**Comment by fhamborg** [comment]
In this case it looks like neither newspaper (which is primarily being used by news-please to extract the publishing date) nor news-please's own set of rules (see https://github.com/fhamborg/news-please/blob/master/newsplease/pipeline/extractor/extractors/date_extractor.py) were able to find a date. In news-please, we only do meta-data-based extraction of the date, and in this particular HTML, afaik there is no meta-data date. We leave the extraction of content-based date mentions to newspaper, so you could open an issue with them.
Please let me know, though, if I oversaw something, and the date actually is in the meta-data (I saw it's partially in the URL, but only year and month).
