### ISSUE TITLE
Configure Depth_limit from Scrapy Middleware

### ISSUE THREAD

**Issue by jacarrasco** [fhamborg/news-please#93]
Hi,
I was thinking on modify the code, in order to add to the config file the Scrapy depth_limit. With that, it would be possible to select to crawl just to an specific layer.
As I understand, the best way is using this middleware.
http://doc.scrapy.org/en/latest/topics/spider-middleware.html#module-scrapy.spidermiddlewares.depth

But i wanted to ask if you is, where in the news-please are you overwriting the Scrapy middleware settings? Is there any specific file you recommend to modify it just to have it in an organized way?

Mainly, what i see when i launch news-please in debug mode is that some scrapy options are being overwritten and i just would like to modify the depth_limit option as well.
If you can give any advice or help i would really appreciate it.

Thank you!

**[scrapy.crawler:38|INFO] Overridden settings: {'BOT_NAME': 'news-please', 'CONCURRENT_REQUESTS_PER_DOMAIN': 4, 'LOG_ENABLED': False, 'LOG_FILE': 'news-please.log', 'LOG_FORMAT': '[%(name)s:%(lineno)d|%(levelname)s] %(message)s', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'newsplease.crawler.spiders', 'ROBOTSTXT_OBEY': True, 'SPIDER_MODULES': ['newsplease.crawler.spiders'], 'USER_AGENT': 'news-please (+http://www.example.com/)'}**

[scrapy.middleware:48|INFO] Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.spiderstate.SpiderState']
[scrapy.middleware:48|INFO] Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
[scrapy.middleware:48|INFO] Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 **'scrapy.spidermiddlewares.depth.DepthMiddleware']**

**Comment by fhamborg** [comment]
You can set any scrapy setting simply in the Scrapy section of the config.cfg file. Please feel free to reopen this issue in case this does not solve your issue
