### ISSUE TITLE
Can I crawl a root site?

### ISSUE THREAD

**Issue by truenodeverano** [fhamborg/news-please#94]
Hi,

Thanks for creating news-please. I'd like to crawl root sites and then specific article. Is it possible to use cnn.com or scmagazine.com as the input and then get back a list of news articles with the different parts news-please extracts?

Thank you!

**Comment by fhamborg** [comment]
That's exactly what the crawler mode does (https://github.com/fhamborg/news-please#run-the-crawler-via-the-cli)

**Comment by truenodeverano** [comment]
I'm sorry Felix. I meant running it from python.

**Comment by truenodeverano** [comment]
Thank you Felix. I wanted to run it from python but I think I can use it through the CLI just the same. Thanks again and my apologies for the triviality of the question.

**Comment by fhamborg** [comment]
No worries! :-) Currently, only the CLI mode supports the full website crawling, the other modes don't.

**Comment by jeongwhanchoi** [comment]
Hello, Felis :]
I wanna crawl articles from a root URL.
Are there any examples running the crawler via the CLI?

**Comment by tomkirk6422** [comment]
I am in the same boat as jeongwhanchoi, i am unable to find the 'data' folder with the json files after running it on the CLI with default example URLs
